/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.UsuarioDAO;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Usuario;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;

/**
 *
 * @author osmar
 */
public class JDialogUsuario extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    UsuarioDAO controle = new UsuarioDAO();
    ArrayList<Usuario> listaUsuarios = new ArrayList<>();

    /**
     * Creates new form JDialogFuncionario
     */
    public JDialogUsuario(Frame frame, boolean bln) {
        super(frame, bln);
        initComponents();
//        listaUsuarios.clear();
//        listaUsuarios.addAll(controle.listarTodos());
//        
        usuarioList.clear();
        usuarioList.addAll(controle.listarTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SistemaReiDoGeloPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SistemaReiDoGeloPU").createEntityManager();
        usuarioQuery = java.beans.Beans.isDesignTime() ? null : SistemaReiDoGeloPUEntityManager.createQuery("SELECT u FROM Usuario u");
        usuarioList = observableList(new ArrayList<>());
        jPanel1 = new javax.swing.JPanel();
        labUsuario = new javax.swing.JLabel();
        txtBuscarUsuario = new javax.swing.JTextField();
        botPesquisarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUs = new javax.swing.JTable();
        botAdicionar = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 415));

        labUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labUsuario.setText("Usuários");

        txtBuscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botPesquisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pesquisar-24.png"))); // NOI18N
        botPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarUsuarioActionPerformed(evt);
            }
        });

        tabUs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usuarioList, tabUs);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usCodus}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usUsuario}"));
        columnBinding.setColumnName("Usuário");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usNome}"));
        columnBinding.setColumnName(" Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usEmail}"));
        columnBinding.setColumnName("E-mail");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usTelefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usStatus}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabUs);
        if (tabUs.getColumnModel().getColumnCount() > 0) {
            tabUs.getColumnModel().getColumn(1).setResizable(false);
            tabUs.getColumnModel().getColumn(2).setResizable(false);
        }

        botAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-adicionar-grupo-de-usuários-homem-homem-24.png"))); // NOI18N
        botAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarActionPerformed(evt);
            }
        });

        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete_remove_bin_icon-icons.com_72400.png"))); // NOI18N
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(botPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(botAdicionar)
                        .addGap(33, 33, 33)
                        .addComponent(botExcluir)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botPesquisarUsuario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labUsuario)
                        .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(816, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarActionPerformed
        // TODO add your handling code here:
        Usuario u = null;
        JDialogInserirUsuario tela = new JDialogInserirUsuario(null, true, u);
        tela.setVisible(true);

        usuarioList.clear();
        usuarioList.addAll(controle.listarTodos());

    }//GEN-LAST:event_botAdicionarActionPerformed

    public void editar() {
        int linha = -1;
        linha = tabUs.getSelectedRow();

        if (linha != -1) {
            Usuario us = usuarioList.get(linha);
            JDialogInserirUsuario tela = new JDialogInserirUsuario(null, true, us);
            tela.setVisible(true);

            usuarioList.clear();
            usuarioList.addAll(controle.listarTodos());
        }
        atualizar();
    }

    public void delete() {
        int resposta;
        int linha, cod;
        linha = tabUs.getSelectedRow();

        if (linha != -1) {
            usuario = usuarioList.get(linha);
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
            if (resposta == JOptionPane.YES_OPTION) {
                controle.excluir(usuario);
                usuarioList.clear();
                usuarioList.addAll(controle.listarTodos());
                tabUs.updateUI();
            } else {
                JOptionPane.showMessageDialog(this, "SELECIONE UM CLIENTE NA TABELA PARA EXCLUIR");
            }

        }
    }
    private void botPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarUsuarioActionPerformed
        // TODO add your handling code here:
        int linha = -1;
        linha = tabUs.getSelectedRow();
        if (linha != -1) {
            usuario = usuarioList.get(linha);
            txtBuscarUsuario.setText(usuario.getUsNome());
//            JOptionPane.showMessageDialog(null, String.valueOf(usuario.getUsNome()));

        } 

        usuarioList.clear();
        usuarioList.addAll(controle.consultarPorNome(txtBuscarUsuario.getText()));
//        System.out.println(listaUsuarios.size());
//        System.out.println(listaUsuarios);
//        usuarioList1.clear();
//        usuarioList1.addAll(listaUsuarios);

//        int linha = -1;
//        linha = tabCliente.getSelectedRow();
//        if (linha != -1) {
//            cliente = listaClientes.get(linha);
//            txtBuscarCliente.setText(cliente.getCliNome());
//
//        }
////        cliente.setCliNome(txtBuscarCliente.getText());
////      //  controle.findCliente(codCli);
//        listaClientes.clear();
//        listaClientes.addAll(controle.consultarPorNome(txtBuscarCliente.getText()));
//        System.out.println(listaClientes.size());
//        clienteList.clear();
//        clienteList.addAll(listaClientes);
//        
    }//GEN-LAST:event_botPesquisarUsuarioActionPerformed

    private void tabUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUsMouseClicked
        // TODO add your handling code here:
//        if (evt.getClickCount() == 2) {
//            int linha = tabUs.getSelectedRow();
//
//            if (linha != -1) {
//                Usuario us = usuarioList.get(linha);
//                JDialogInserirUsuario tela = new JDialogInserirUsuario(null, true, us);
//                tela.setVisible(true);
//
//                usuarioList.clear();
//                usuarioList.addAll(controle.listarTodos());
//            }
//
//            atualizar();
//        }
    }//GEN-LAST:event_tabUsMouseClicked

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        // TODO add your handling code here:

        int resposta;

        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            usuarioList.get(tabUs.getSelectedRow());
            if(tabUs.getSelectedRow() != -1)
            controle.excluir( usuarioList.get(tabUs.getSelectedRow()));
       
        }
    }//GEN-LAST:event_botExcluirActionPerformed

    private void atualizar() {

        usuarioList.clear();
        usuarioList.addAll(controle.listarTodos());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaPrincipalGerente().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(JDialogUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SistemaReiDoGeloPUEntityManager;
    private javax.swing.JButton botAdicionar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botPesquisarUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labUsuario;
    private javax.swing.JTable tabUs;
    private javax.swing.JTextField txtBuscarUsuario;
    private java.util.List<modelo.Usuario> usuarioList;
    private javax.persistence.Query usuarioQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
