package visao;

import controle.DespesaDAO;
import java.awt.Frame;
import java.util.ArrayList;
import modelo.Despesa;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;

/**
 *
 * @author osmar
 */
public class JDialogDespesas extends javax.swing.JDialog {

    Despesa despesa = new Despesa();
    DespesaDAO controle = new DespesaDAO();
    ArrayList<Despesa> listaDesp = new ArrayList();

    /**
     * Creates new form JDialogDespesas
     */
    
    
    public JDialogDespesas(Frame frame, boolean bln) {

        super(frame, bln);
        initComponents();
        despesaList.clear();
        despesaList.addAll(controle.listarTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SistemaReiDoGeloPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SistemaReiDoGeloPU").createEntityManager();
        despesaQuery = java.beans.Beans.isDesignTime() ? null : SistemaReiDoGeloPUEntityManager.createQuery("SELECT d FROM Despesa d");
        formatRenderer1 = new renderizador.FormatRenderer();
        despesaList = observableList (new ArrayList<>());
        jPanel1 = new javax.swing.JPanel();
        labCliente = new javax.swing.JLabel();
        botPesquisarFunc = new javax.swing.JButton();
        botAdicionarFunc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDespesas = new javax.swing.JTable();
        txtBuscarDesp = new javax.swing.JTextField();
        botAdicionarTipoDesp = new javax.swing.JButton();

        formatRenderer1.setText("formatRenderer1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 415));

        labCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labCliente.setText("Despesas");

        botPesquisarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pesquisar-24.png"))); // NOI18N
        botPesquisarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarFuncActionPerformed(evt);
            }
        });

        botAdicionarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-adicionar-grupo-de-usuários-homem-homem-24.png"))); // NOI18N
        botAdicionarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarFuncActionPerformed(evt);
            }
        });

        tabDespesas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, despesaList, tabDespesas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${despDataVencimento}"));
        columnBinding.setColumnName("Data Vencimento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${despDataPagamento}"));
        columnBinding.setColumnName(" Data Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${despDescricao}"));
        columnBinding.setColumnName(" Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipodespesaTpdespCod}"));
        columnBinding.setColumnName("Tipo Despesa");
        columnBinding.setColumnClass(modelo.TipoDespesa.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${despVlPago}"));
        columnBinding.setColumnName(" Valor");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuarioUsCodusuario}"));
        columnBinding.setColumnName("Usuario");
        columnBinding.setColumnClass(modelo.Usuario.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${despStatusPagamento}"));
        columnBinding.setColumnName("Status Pagamento");
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDespesasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabDespesas);
        if (tabDespesas.getColumnModel().getColumnCount() > 0) {
            tabDespesas.getColumnModel().getColumn(4).setCellRenderer(formatRenderer1);
        }

        txtBuscarDesp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botAdicionarTipoDesp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botAdicionarTipoDesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/slot-of-bills24.png"))); // NOI18N
        botAdicionarTipoDesp.setText("TIPO DE DESP.");
        botAdicionarTipoDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarTipoDespActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(284, 284, 284)
                            .addComponent(botAdicionarFunc)
                            .addGap(18, 18, 18)
                            .addComponent(botAdicionarTipoDesp))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(labCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscarDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(botPesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labCliente)
                        .addComponent(txtBuscarDesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botPesquisarFunc))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botAdicionarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botAdicionarTipoDesp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(824, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botAdicionarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarFuncActionPerformed
        // TODO add your handling code here:
        Despesa d = null;
        JDialogInserirDespesas tela = new JDialogInserirDespesas(null,true, d);
        tela.setVisible(true);
        despesaList.clear();
        despesaList.addAll(controle.listarTodos());
    }//GEN-LAST:event_botAdicionarFuncActionPerformed

    private void botPesquisarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarFuncActionPerformed
        // TODO add your handling code here:
        int linha = -1;
        linha = tabDespesas.getSelectedRow();

        if (linha != -1) {
            despesa = listaDesp.get(linha);
            txtBuscarDesp.setText(despesa.getDespDescricao());
        }

        listaDesp.clear();
        listaDesp.addAll(controle.consultarPorNome(txtBuscarDesp.getText()));
        System.out.println(listaDesp.size());
        despesaList.clear();
        despesaList.addAll(listaDesp);

    }//GEN-LAST:event_botPesquisarFuncActionPerformed

    private void botAdicionarTipoDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarTipoDespActionPerformed
        JDialogTipoDespesa tela = new JDialogTipoDespesa(null,true);
        tela.setVisible(true);
    }//GEN-LAST:event_botAdicionarTipoDespActionPerformed

    private void tabDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDespesasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int linha = tabDespesas.getSelectedRow();
            
            if(linha != -1){
                System.out.println("Entrou no 2 if");
                Despesa desp = despesaList.get(linha);
                JDialogInserirDespesas tela = new JDialogInserirDespesas(null, true, desp);
                 tela.setVisible(true);
                 
                 despesaList.clear();
                 despesaList.addAll(controle.listarTodos());
            }
            
        }
    }//GEN-LAST:event_tabDespesasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SistemaReiDoGeloPUEntityManager;
    private javax.swing.JButton botAdicionarFunc;
    private javax.swing.JButton botAdicionarTipoDesp;
    private javax.swing.JButton botPesquisarFunc;
    private java.util.List<modelo.Despesa> despesaList;
    private javax.persistence.Query despesaQuery;
    private renderizador.FormatRenderer formatRenderer1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labCliente;
    private javax.swing.JTable tabDespesas;
    private javax.swing.JTextField txtBuscarDesp;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
