/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.TipoDespesaDAO;
import java.awt.Component;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.TipoDespesa;

/**
 *
 * @author osmar
 */
public class JDialogInserirTipoDespesa extends javax.swing.JDialog {

    TipoDespesa tipoDespesa = new TipoDespesa();
    TipoDespesaDAO controle = new TipoDespesaDAO();

    public JDialogInserirTipoDespesa(java.awt.Frame parent, boolean modal, TipoDespesa tpdesp) {
        super(parent, modal);
        initComponents();

        if (tpdesp == null) {
            liberarCampos(true);
        } else {
            this.tipoDespesa = tpdesp;
            List<TipoDespesa> listTipoDesp = controle.listarTodos();
            txtTipo.setText(tipoDespesa.getTpdespDescricao());
            liberarCampos(false);
        }
    }

    public JDialogInserirTipoDespesa() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botSalvar = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        botExcluir = new javax.swing.JButton();
        botEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tipo:");

        botSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-salvar-30.png"))); // NOI18N
        botSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalvarActionPerformed(evt);
            }
        });

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete_remove_bin_icon-icons.com_72400.png"))); // NOI18N
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });

        botEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-lápis-24.png"))); // NOI18N
        botEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(botEditar)
                        .addGap(18, 18, 18)
                        .addComponent(botExcluir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botEditar, botExcluir, botSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botSalvar)
                    .addComponent(botEditar)
                    .addComponent(botExcluir))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botEditar, botExcluir, botSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void botSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalvarActionPerformed
        // TODO add your handling code here:
//        tipoDespesa.setTpdespCod(Integer.parseInt(txtCodigo.getText()));
        List<TipoDespesa> listTipoDesp = controle.listarTodos();
        int i = 0;

        tipoDespesa.setTpdespDescricao(txtTipo.getText());
        for (TipoDespesa tipoDespesa1 : listTipoDesp) {
            if (tipoDespesa1.getTpdespDescricao().toUpperCase().equals(tipoDespesa.getTpdespDescricao().toUpperCase())) {
                i++;
            }
        }
        if (i == 0) {
            tipoDespesa.setTpdespStatus("A");
            controle.salvarNovo(tipoDespesa);
            JOptionPane.showMessageDialog(null, "Tipo de Despesa Salva");
        }
        dispose();
    }//GEN-LAST:event_botSalvarActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        //         TODO add your handling code here:
        liberarCampos(true);
        int resposta;

        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {

            controle.excluir(tipoDespesa);
           dispose();
        }
    }//GEN-LAST:event_botExcluirActionPerformed

    private void botEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEditarActionPerformed
        // TODO add your handling code here:
        liberarCampos(true);
//        int linha = -1;
//        linha = tabTipoDespesa.getSelectedRow();
//        if (linha != -1) {
//            TipoDespesa Tipodesp = tipoDespesaList.get(linha);
//            JDialogInserirTipoDespesa tela = new JDialogInserirTipoDespesa(null,true);
//            tela.setVisible(true);
//            listaTipoDespesas.clear();
//            listaTipoDespesas.addAll(controle.listarTodos());
//            tipoDespesaList.clear();
//            tipoDespesaList.addAll(listaTipoDespesas);
//        }
    }//GEN-LAST:event_botEditarActionPerformed

    private void liberarCampos(boolean a) {
        for (Component c : jPanel1.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setEditable(a);
            } else if (c instanceof JLabel) {

            } else {

                c.setEnabled(a);
            }

        }

        botSalvar.setEnabled(a);
        botEditar.setEnabled(!a);
        botExcluir.setEnabled(!a);

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogInserirTipoDespesa.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogInserirTipoDespesa.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogInserirTipoDespesa.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogInserirTipoDespesa.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botEditar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
