/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.TipoDespesaDAO;
import java.awt.Frame;
import java.util.ArrayList;
import modelo.TipoDespesa;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;

/**
 *
 * @author osmar
 */
public class JDialogTipoDespesa extends javax.swing.JDialog {

    TipoDespesa tipoDespesa = new TipoDespesa();
    TipoDespesaDAO controle = new TipoDespesaDAO();
    ArrayList<TipoDespesa> listaTipoDespesas = new ArrayList();
    
    /**
     * Creates new form JDialogTipoDespesa
     */
    
    
    public JDialogTipoDespesa(Frame frame, boolean bln) {
        super(frame, bln);
        initComponents();
        tipoDespesaList.clear();
        tipoDespesaList.addAll(controle.listarTodos());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SistemaReiDoGeloPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SistemaReiDoGeloPU").createEntityManager();
        query1 = java.beans.Beans.isDesignTime() ? null : SistemaReiDoGeloPUEntityManager.createQuery("SELECT td FROM TipoDespesa td");
        tipoDespesaList = observableList (new ArrayList<>());
        jPanel = new javax.swing.JPanel();
        labTipoDespesa = new javax.swing.JLabel();
        txtBuscarTipoDesp = new javax.swing.JTextField();
        botPesquisar = new javax.swing.JButton();
        botAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabTipoDespesa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTipoDespesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labTipoDespesa.setText("Tipo de Despesas");

        txtBuscarTipoDesp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pesquisar-24.png"))); // NOI18N
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });

        botAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-adicionar-grupo-de-usuários-homem-homem-24.png"))); // NOI18N
        botAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarActionPerformed(evt);
            }
        });

        tabTipoDespesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tipoDespesaList, tabTipoDespesa);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tpdespDescricao}"));
        columnBinding.setColumnName(" Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabTipoDespesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTipoDespesaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabTipoDespesa);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(txtBuscarTipoDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(botAdicionar)
                        .addGap(458, 458, 458))))
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labTipoDespesa)
                    .addContainerGap(576, Short.MAX_VALUE)))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botPesquisar)
                    .addComponent(txtBuscarTipoDesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(botAdicionar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(labTipoDespesa)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(816, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed
        // TODO add your handling code here:
        int linha = -1;
        linha = tabTipoDespesa.getSelectedRow();

        if (linha != -1) {
            tipoDespesa = listaTipoDespesas.get(linha);
            txtBuscarTipoDesp.setText(tipoDespesa.getTpdespDescricao());
        }

        listaTipoDespesas.clear();
        listaTipoDespesas.addAll(controle.consultarPorDescricao(txtBuscarTipoDesp.getText()));
        System.out.println(listaTipoDespesas.size());
        tipoDespesaList.clear();
        tipoDespesaList.addAll(listaTipoDespesas);
    }//GEN-LAST:event_botPesquisarActionPerformed

    private void botAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarActionPerformed
        // TODO add your handling code here:
        TipoDespesa tpdesp = null;
        JDialogInserirTipoDespesa tela = new JDialogInserirTipoDespesa(null,true,tpdesp);
        tela.setVisible(true);
        tipoDespesaList.clear();
        tipoDespesaList.addAll(controle.listarTodos());
    }//GEN-LAST:event_botAdicionarActionPerformed

    private void tabTipoDespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTipoDespesaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int linha = tabTipoDespesa.getSelectedRow();
            
            if(linha != -1){
                TipoDespesa tpdesp = tipoDespesaList.get(linha);
                JDialogInserirTipoDespesa tela = new JDialogInserirTipoDespesa(null,true,tpdesp);
                tela.setVisible(true);
                
                tipoDespesaList.clear();
                tipoDespesaList.addAll(controle.listarTodos());
            }
        }
    }//GEN-LAST:event_tabTipoDespesaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogTipoDespesa dialog = new JDialogTipoDespesa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SistemaReiDoGeloPUEntityManager;
    private javax.swing.JButton botAdicionar;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labTipoDespesa;
    private javax.persistence.Query query1;
    private javax.swing.JTable tabTipoDespesa;
    private java.util.List<modelo.TipoDespesa> tipoDespesaList;
    private javax.swing.JTextField txtBuscarTipoDesp;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
