/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.UsuarioDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Usuario;
import validacao.ValidaCPF;

/**
 *
 * @author osmar
 */
public class JDialogInserirUsuario extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    UsuarioDAO controle = new UsuarioDAO();

    public JDialogInserirUsuario(Frame frame, boolean bln, Usuario usuario) {

        super(frame, bln);

        initComponents();

        if (usuario == null) {
            liberarCampos(true);
        } else {
            txtNome4.setText(usuario.getUsNome());
            txtEmail.setText(usuario.getUsEmail());
            txtUsuario.setText(usuario.getUsUsuario());
            comboCargo.setSelectedItem(usuario.getUsCargo());
            formatoTelefone.setText(usuario.getUsTelefone());
            passwordSenha.setText(usuario.getUsSenha());
            passwordSenhaConf.setText(usuario.getUsSenha());
            liberarCampos(false);
            this.usuario = usuario;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botSalvar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        labNome = new javax.swing.JLabel();
        txtNome4 = new javax.swing.JTextField();
        labCargo = new javax.swing.JLabel();
        labTelefone = new javax.swing.JLabel();
        formatoTelefone = new javax.swing.JFormattedTextField();
        labEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        labSenha = new javax.swing.JLabel();
        passwordSenha = new javax.swing.JPasswordField();
        labSenhaConf = new javax.swing.JLabel();
        passwordSenhaConf = new javax.swing.JPasswordField();
        comboCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        botSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-salvar-30.png"))); // NOI18N
        botSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalvarActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuário"));

        labNome.setText("Nome:");

        labCargo.setText("Cargo:");

        labTelefone.setText("Telefone:");

        try {
            formatoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labEmail.setText("E-mail:");

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        labUsuario.setText("Usuário:");

        labSenha.setText("Senha:");

        labSenhaConf.setText("Senha:");

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Gerente" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(labUsuario)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(labTelefone)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(formatoTelefone)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labSenhaConf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labCargo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labSenha, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordSenha)
                            .addComponent(passwordSenhaConf)
                            .addComponent(comboCargo, 0, 334, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNome)
                            .addComponent(labEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtNome4))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(txtNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCargo)
                    .addComponent(labTelefone)
                    .addComponent(formatoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labSenha))
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSenhaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordSenhaConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botSalvar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalvarActionPerformed
        // TODO add your handling code here:
        String senha = passwordSenha.getText();

        MessageDigest md;
        try {
            md = MessageDigest.getInstance("SHA-256");
            try {

                byte password[] = md.digest(senha.getBytes("UTF-8"));

                StringBuilder hexString = new StringBuilder();
                for (byte b : password) {
                    hexString.append(String.format("%02X", 0xFF & b));
                }
                String senhahex = hexString.toString();

                System.out.println(senhahex);
                usuario.setUsSenha(senhahex);

            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        usuario.setUsNome(txtNome4.getText());
        usuario.setUsEmail(txtEmail.getText());
        usuario.setUsCargo((String) comboCargo.getSelectedItem());
        usuario.setUsTelefone(formatoTelefone.getText());
        usuario.setUsUsuario(txtUsuario.getText());
        usuario.setUsStatus("A");
        if (passwordSenha.getText().equals(passwordSenhaConf.getText())) {
//            JOptionPane.showMessageDialog(this, "Senhas iguais");
        } else {
            JOptionPane.showMessageDialog(this, "Senhas não são iguais");
            passwordSenha.setText("");
            passwordSenhaConf.setText("");
            passwordSenha.requestFocus();
        }
        if (txtNome4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não preencheu o campo obrigatório: Nome.");
            return;
        }
        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não preencheu o campo obrigatório: E-mail.");
            return;
        }
        if (passwordSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não preencheu o campo obrigatório: Senha.");
            return;
        }
        if (txtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não preencheu o campo obrigatório: Usuário.");
            return;
        }

        try {
            controle.salvarNovo(usuario);
            JOptionPane.showMessageDialog(null, "Usuário Salvo");
            dispose();
        } catch (Exception ex) {
            System.out.println(ex);
            //JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botSalvarActionPerformed
    private void liberarCampos(boolean a) {
        for (Component c : jPanel1.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setEditable(a);
            } else if (c instanceof JLabel) {

            } else {

                c.setEnabled(a);
            }

        }
        for (Component c : jPanel9.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setEditable(a);
            } else if (c instanceof JLabel) {

            } else {

                c.setEnabled(a);
            }

        }

        botSalvar.setEnabled(a);

    }
    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed

    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        int opcao = -1;

        System.out.println(txtEmail.getText());
        List<Usuario> usuarioo = controle.consultarPorEmailUs(txtEmail.getText());

        if (!usuarioo.isEmpty()) {
            //           System.out.println("nao vazio");
            int contador = 0;
            int contador2 = 0;

            for (Usuario u : usuarioo) {
                if (u.getUsStatus().equals("A")) {
                    contador += 1;
                    this.usuario = u;
                } else if (u.getUsStatus().equals("I")) {
                    contador2 += 1;
                    this.usuario = u;
                }
            }

            if (contador > 0) {
                txtEmail.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, "Já existe um cadastro para esse e-mail.");
                txtNome4.setText(usuario.getUsNome());
                txtEmail.setText(usuario.getUsEmail());
                txtUsuario.setText(usuario.getUsUsuario());
                comboCargo.setSelectedItem(usuario.getUsCargo());
                formatoTelefone.setText(usuario.getUsTelefone());
                passwordSenha.setText(usuario.getUsSenha());
                passwordSenhaConf.setText(usuario.getUsSenha());
            } else {
                txtEmail.setBackground(Color.white);
            }

            if (usuario.getUsStatus().equals("I")) {

                opcao = JOptionPane.showConfirmDialog(this, "Deseja reativar o usuário?", "Usuário inativo", 0);

                if (opcao == 0) {
                    System.out.println("Entrou recuperação de dados" + "");
//                    JOptionPane.showMessageDialog(this, "Já existe um cadastro para esse e-mail.");
                    txtEmail.setBackground(Color.red);
                    txtNome4.setText(usuario.getUsNome());
                    txtEmail.setText(usuario.getUsEmail());
                    txtUsuario.setText(usuario.getUsUsuario());
                    comboCargo.setSelectedItem(usuario.getUsCargo());
                    formatoTelefone.setText(usuario.getUsTelefone());
                    passwordSenha.setText(usuario.getUsSenha());
                    passwordSenhaConf.setText(usuario.getUsSenha());
                }
            }
        } else {
            System.out.println("vazio");
            txtEmail.setBackground(Color.white);
//                botSalvar.setEnabled(true);
        }


    }//GEN-LAST:event_txtEmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botSalvar;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JFormattedTextField formatoTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labCargo;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labSenha;
    private javax.swing.JLabel labSenhaConf;
    private javax.swing.JLabel labTelefone;
    private javax.swing.JLabel labUsuario;
    private javax.swing.JPasswordField passwordSenha;
    private javax.swing.JPasswordField passwordSenhaConf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome4;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
