/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ProdutoDAO;
import java.awt.Frame;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.Produto;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;

/**
 *
 * @author osmar
 */
public class JDialogProduto extends javax.swing.JDialog {

    Produto produto = new Produto();
    TableModel model = new TableModel();
    ProdutoDAO controle = new ProdutoDAO();
    ArrayList<Produto> listaProd = new ArrayList();

    /**
     * Creates new form JDialogProduto
     */
    public JDialogProduto(Frame frame, boolean bln) {

        super(frame, bln);
        initComponents();
        listaProd.clear();
       // listaProd.addAll(controle.listarTodos());
        produtoList.clear();
        //produtoList.addAll(controle.listarTodos());
        System.out.println(listaProd.size());
        tabProd.setModel(model);
        atualizar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager2 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SistemaReiDoGeloPU").createEntityManager();
        query1 = java.beans.Beans.isDesignTime() ? null : entityManager2.createQuery("select p from Produto p");
        produtoList = observableList(new ArrayList<>());
        jPanel1 = new javax.swing.JPanel();
        labProd = new javax.swing.JLabel();
        botPesquisarProd = new javax.swing.JButton();
        botAdicionarProd = new javax.swing.JButton();
        txtProd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProd = new javax.swing.JTable();
        formatRenderer1 = new renderizador.FormatRenderer();
        formatRenderer21 = new renderizador.FormatRenderer2();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 415));

        labProd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labProd.setText("Produtos");

        botPesquisarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pesquisar-24.png"))); // NOI18N
        botPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarProdActionPerformed(evt);
            }
        });

        botAdicionarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-adicionar-grupo-de-usuários-homem-homem-24.png"))); // NOI18N
        botAdicionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarProdActionPerformed(evt);
            }
        });

        txtProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tabProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Descrição", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabProd);
        if (tabProd.getColumnModel().getColumnCount() > 0) {
            tabProd.getColumnModel().getColumn(1).setCellRenderer(formatRenderer21);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(formatRenderer21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286)
                        .addComponent(botAdicionarProd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(botPesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labProd)
                        .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botPesquisarProd))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botAdicionarProd)
                    .addComponent(formatRenderer21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(824, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botAdicionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarProdActionPerformed
        // TODO add your handling code here:
        Produto p = null;
        JDialogInserirProduto tela = new JDialogInserirProduto(null, true, p);
        tela.setVisible(true);
        atualizar();
    }//GEN-LAST:event_botAdicionarProdActionPerformed

    public void editar() {
        int linha = -1;
        linha = tabProd.getSelectedRow();
        if (("" + produtoList.get(linha).getProdStatus()).equals("null")) {

            if (linha != -1) {
                Produto prod = produtoList.get(linha);
                JDialogInserirProduto tela = new JDialogInserirProduto(null, true, prod);
                tela.setVisible(true);

                produtoList.clear();
                produtoList.addAll(controle.listarTodos());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não é possível alterar produto indisponível!");
        }
        atualizar();
    }

    public void delete() {
        int resposta;
        int linha, cod;
        linha = tabProd.getSelectedRow();

        if (("" + produtoList.get(linha).getProdStatus()).equals("null")) {
            if (linha != -1) {

                produto = produtoList.get(linha);
                resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
                if (resposta == JOptionPane.YES_OPTION) {
                    produto.setProdStatus("I");
                    controle.excluir(produto);
                    produtoList.clear();
                    produtoList.addAll(controle.listarTodos());
                    tabProd.updateUI();
                }
            } else {
                JOptionPane.showMessageDialog(this, "SELECIONE UM PRODUTO NA TABELA PARA EXCLUIR");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não é possível excluir produto indisponível");
        }
    }
    private void botPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarProdActionPerformed
        // TODO add your handling code here:
        int linha = -1;
        linha = tabProd.getSelectedRow();

        if (linha != -1) {
            produto = listaProd.get(linha);
            txtProd.setText(produto.getProdDescricao());
            txtProd.setText(String.valueOf(produto.getProdCodprod()));
        }

        listaProd.clear();
        listaProd.addAll(controle.consultarPorDescricao(txtProd.getText()));
//        listaProd.addAll (controle.consultarPorCodProd(String.valueOf(txtProd.getText())));
        System.out.println(listaProd.size());
        produtoList.clear();
        produtoList.addAll(listaProd);
    }//GEN-LAST:event_botPesquisarProdActionPerformed

    private void tabProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int linha = tabProd.getSelectedRow();

            if (linha != -1) {
                Produto prod = produtoList.get(linha);
                JDialogInserirProduto tela = new JDialogInserirProduto(null, true, prod);
                tela.setVisible(true);

                produtoList.clear();
                produtoList.addAll(controle.listarTodos());

            }

            atualizar();
        }
    }//GEN-LAST:event_tabProdMouseClicked

    private void atualizar() {
        listaProd.clear();
        listaProd.addAll(controle.listarTodos());
        produtoList.clear();
        produtoList.addAll(controle.listarTodos());

        model.limpar();

        if (produtoList != null) {
            for (Produto p : produtoList) {
                model.addRow(p);
            }
        }

        // model.limpar();
        System.out.println("Lista Produto" + produtoList);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAdicionarProd;
    private javax.swing.JButton botPesquisarProd;
    private javax.persistence.EntityManager entityManager2;
    private renderizador.FormatRenderer formatRenderer1;
    private renderizador.FormatRenderer2 formatRenderer21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labProd;
    private java.util.List<modelo.Produto> produtoList;
    private javax.persistence.Query query1;
    private javax.swing.JTable tabProd;
    private javax.swing.JTextField txtProd;
    // End of variables declaration//GEN-END:variables
}
