/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CaixaDAO;
import controle.UsuarioDAO;
import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import modelo.Usuario;
import javax.swing.JOptionPane;
import modelo.Caixa;

public class TelaLogin extends javax.swing.JFrame {

    Usuario us = new Usuario();
    private Caixa caixa = new Caixa();
    UsuarioDAO controle = new UsuarioDAO();
    CaixaDAO controleCaixa = new CaixaDAO();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin(Object object, boolean b) {
        super();
    }

    public TelaLogin() {

        initComponents();
        passwordSenha.setText("");
        UsuarioDAO conta = new UsuarioDAO();
        Usuario u;
        long valor = conta.conta();
        if (valor == 0) {
            JDialogInserirUsuario x = new JDialogInserirUsuario(null, true, null);
            x.setVisible(true);
        } else {
            txtUsuario.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
            passwordSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labUsuario = new javax.swing.JLabel();
        labSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        botEntrar = new javax.swing.JButton();
        passwordSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo_redimensionado.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        labUsuario.setText("Usuário:");

        labSenha.setText("Senha:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        botEntrar.setBackground(new java.awt.Color(0, 102, 153));
        botEntrar.setText("Entrar");
        botEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEntrarActionPerformed(evt);
            }
        });

        passwordSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSenhaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo_redimensionado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(botEntrar)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labUsuario)
                            .addComponent(labSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(passwordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(93, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSenha)
                    .addComponent(passwordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botEntrar)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGap(140, 140, 140)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEntrarActionPerformed
        // TODO add your handling code here:
        String senha = passwordSenha.getText();
        UsuarioDAO contUs = new UsuarioDAO();

        MessageDigest md;
        try {
            md = MessageDigest.getInstance("SHA-256");
            try {
                byte password[] = md.digest(senha.getBytes("UTF-8"));

                StringBuilder hexString = new StringBuilder();
                for (byte b : password) {
                    hexString.append(String.format("%02X", 0xFF & b));
                }
                String senhahex = hexString.toString();
                this.us = contUs.logarUsuario(txtUsuario.getText(), senhahex);
                System.out.println(senhahex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (this.us != null) {

            if (this.us.getUsCargo().toLowerCase().equals("gerente")) {
                TelaPrincipalGerente telaGerente = new TelaPrincipalGerente(this.us);
                telaGerente.setVisible(true);
                //If(caixa.controle.buscar().isnull() || caixa.controle....isEmpty())
                Caixa caixa = null;
                if (controleCaixa.buscar().isEmpty() || controleCaixa.buscar() == null) {
                    
                }else{
                    caixa = (Caixa) controleCaixa.buscar().get(0);
                }
                controleCaixa.setCaixa(caixa);
                dispose();
            } else {
                TelaPrincipalAtendente telaAtendente = new TelaPrincipalAtendente(this.us);
                telaAtendente.setVisible(true);

            }
        } else {
            txtUsuario.setText("");
            passwordSenha.setText("");
            txtUsuario.requestFocus();
            passwordSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
            txtUsuario.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
            txtUsuario.requestFocus();

        }

//        String usuario;
//        String senha;
//        
//       
//        us.setUsUsuario(txtUsuario.getText());
//        us.setUsSenha(String.valueOf(passwordSenha.getPassword()));
////        controle.getValidarUsuario(fun);
//        if(txtUsuario.getText().equals("admin") && passwordSenha.getText().equals("admin")){
//           String x = "admin";
//           dispose();
//           TelaPrincipalGerente tela = new TelaPrincipalGerente();
//           tela.setVisible(true);
//        } else{
//            JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos.");
//        }
        /*  try{
            
        }*/

    }//GEN-LAST:event_botEntrarActionPerformed

    private void passwordSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSenhaActionPerformed
        // TODO add your handling code here:
        passwordSenha.setText("");
    }//GEN-LAST:event_passwordSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TelaLogin log = new TelaLogin();
            log.setVisible(true);
//            new TelaPrincipalGerente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labSenha;
    private javax.swing.JLabel labUsuario;
    private javax.swing.JPasswordField passwordSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
