/*
 */
package visao;

import controle.UsuarioDAO;
import fabrica.FabricaRelatorio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Caixa;
import modelo.Usuario;

/**
 *
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 *
 * @author osmar
 */
public class TelaPrincipalAtendente extends javax.swing.JFrame {

    private Usuario usuario;
    private Caixa caixa;
    UsuarioDAO ud = new UsuarioDAO();
    Usuario usuLogado = null;
    public TelaPrincipalAtendente() {
        
         initComponents();
         usuLogado = ud.getUsuarioLogado();
         
         
//         TelaPrincipalGerente principal = new TelaPrincipalGerente();
//         principal.setVisible(true);

        
    
        TelaLogin log = new TelaLogin();
        log.setVisible(true);
        if (log.isVisible()) {

        } else {

            UsuarioDAO controle = new UsuarioDAO();

            // Funcionario.controle(10);
            Usuario us = new Usuario();

            us.setUsNome("Marcia");
            us.setUsUsuario("marcia");
            us.setUsSenha("mudar123");

             try {
                 controle.salvarNovo(us);
             } catch (Exception ex) {
                 Logger.getLogger(TelaPrincipalGerente.class.getName()).log(Level.SEVERE, null, ex);
             }

            //  fazendo a exclusão do usuário de código 6
//            if (controle.excluir(6)) {
//                System.out.println("Usuario 6 excluído com sucesso!!!");
//            } else {
//                System.out.println("Usuario 6 excluído sem sucesso???");
//            }

            Usuario usAlterar = new Usuario();

            // defino o código do registro que será alterado no banco
            usAlterar.setUsCodusuario(2);
            // preenche os outros atributos com seus valores
            usAlterar.setUsNome("José Antonio de Oliveira");
            usAlterar.setUsUsuario("zeanta");
            usAlterar.setUsSenha("123");

//            controle.salvarAlteracao(usAlterar);
//
//            int codigo = 8;
//
//               Usuario us = controle.buscar(cod);
//            /*          if(fun == null)
//          {
//              System.out.println("O usuário com o código "+codigo+" não existe");
//          }
//          else
//          {   
//              System.out.println(fun);
//          }*/
//            Usuario fun2 = new Usuario();
//
//            fun2.setFunNome("Antonio da Silva");
//            fun2.setFunUsuario("tonho");
//            fun2.setFunSenha("654321");
//
//            // Funcionario.setUltimoCodigo(1000);
//            System.out.println(fun);
//            System.out.println(fun2);

            /**
             * controle.listarTodos - traz uma lista com todos os usuários
             * cadastrados na tabela usuario pega usuário a usuário e colocar em
             * user
             */
            /*for (Funcionario fun : ControleFuncionario.listarTodos()) {
            System.out.println(fun);
        }*/
            System.out.println("quantidade -" + controle.contarUs());
        }

        /* @author osmar
         */
        /**
         * Creates new form TelaPrincipal
         */
   }

    TelaPrincipalAtendente(Usuario usuario) {
        initComponents(); 
        this.usuario = usuario; 
        this.usuLogado = usuario;
        this.caixa = caixa;
        
//        if(this.usuario.getUsCargo().equals("Atendente")){
//            
//            botUsuarios1.setText("Mudar senha");
//        }
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botUsuarios1 = new javax.swing.JButton();
        botCliente = new javax.swing.JButton();
        botAbrirCaixa = new javax.swing.JButton();
        botVendas = new javax.swing.JButton();
        botVendas1 = new javax.swing.JButton();
        botRealizarRecebimento = new javax.swing.JButton();
        botDespesa = new javax.swing.JButton();
        botFecharCaixa = new javax.swing.JButton();
        botRelatorioRecebimento = new javax.swing.JButton();
        botRelatorioCaixa = new javax.swing.JButton();
        botRelatorioVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REI DO GELO - HOME");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1300, 750));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        conteudo.setBackground(new java.awt.Color(0, 0, 0));
        conteudo.setLayout(new java.awt.GridLayout(2, 10, 15, 15));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 15, 15));

        botUsuarios1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-chave-2-50.png"))); // NOI18N
        botUsuarios1.setText("Mudar senha");
        botUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botUsuarios1ActionPerformed(evt);
            }
        });
        jPanel1.add(botUsuarios1);

        botCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-adicionar-grupo-de-usuários-homem-homem-50.png"))); // NOI18N
        botCliente.setText("Clientes");
        botCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botCliente);

        botAbrirCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadeado_livre.png"))); // NOI18N
        botAbrirCaixa.setText("Abrir Caixa");
        botAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAbrirCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(botAbrirCaixa);

        botVendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vendas64.png"))); // NOI18N
        botVendas.setText("Realizar Venda");
        botVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVendasActionPerformed(evt);
            }
        });
        jPanel1.add(botVendas);

        botVendas1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botVendas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vendas64.png"))); // NOI18N
        botVendas1.setText("Consultar Vendas");
        botVendas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVendas1ActionPerformed(evt);
            }
        });
        jPanel1.add(botVendas1);

        botRealizarRecebimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botRealizarRecebimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixaregis64.png"))); // NOI18N
        botRealizarRecebimento.setText("Realizar Recebimento");
        botRealizarRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRealizarRecebimentoActionPerformed(evt);
            }
        });
        jPanel1.add(botRealizarRecebimento);

        botDespesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pasta-50.png"))); // NOI18N
        botDespesa.setText("Pagamento de Despesas");
        botDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDespesaActionPerformed(evt);
            }
        });
        jPanel1.add(botDespesa);

        botFecharCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadeado.png"))); // NOI18N
        botFecharCaixa.setText("Fechar Caixa");
        botFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFecharCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(botFecharCaixa);

        botRelatorioRecebimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botRelatorioRecebimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-relatório-de-lucro-80_1.png"))); // NOI18N
        botRelatorioRecebimento.setText("Rel. de Recebimentos");
        botRelatorioRecebimento.setPreferredSize(new java.awt.Dimension(193, 89));
        botRelatorioRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRelatorioRecebimentoActionPerformed(evt);
            }
        });
        jPanel1.add(botRelatorioRecebimento);

        botRelatorioCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botRelatorioCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-relatório-de-lucro-80.png"))); // NOI18N
        botRelatorioCaixa.setText("Relatório Caixa");
        botRelatorioCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRelatorioCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(botRelatorioCaixa);

        botRelatorioVendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-relatório-de-lucro-80.png"))); // NOI18N
        botRelatorioVendas.setText("Relatório Vendas");
        botRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRelatorioVendasActionPerformed(evt);
            }
        });
        jPanel1.add(botRelatorioVendas);

        conteudo.add(jPanel1);

        getContentPane().add(conteudo);

        setLocation(new java.awt.Point(0, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void botRelatorioRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRelatorioRecebimentoActionPerformed
        // TODO add your handling code here:
        JDialogRelatorioDataRecebimento tela = new JDialogRelatorioDataRecebimento(null, true);
        tela.setVisible(true);
    
    }//GEN-LAST:event_botRelatorioRecebimentoActionPerformed

    private void botRelatorioCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRelatorioCaixaActionPerformed
        // TODO add your handling code here:
        JDialogRelatorioDataCaixa tela = new JDialogRelatorioDataCaixa(null,true);
        tela.setVisible(true);
       
//        FabricaRelatorio.abrirJrxm("../relatorio/caixa.jrxml");
    }//GEN-LAST:event_botRelatorioCaixaActionPerformed

    private void botFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFecharCaixaActionPerformed
        // TODO add your handling code here:
        JDialogFecharCaixa tela = new JDialogFecharCaixa(null,true,this.caixa,this.usuario);
        tela.setVisible(true);
    }//GEN-LAST:event_botFecharCaixaActionPerformed

    private void botDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDespesaActionPerformed
        // TODO add your handling code here:
        JDialogDespesas tela = new JDialogDespesas(null,true);
        tela.setVisible(true);
    }//GEN-LAST:event_botDespesaActionPerformed

    private void botVendas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVendas1ActionPerformed
        // TODO add your handling code here:
        JDialogConsultarVenda tela = new JDialogConsultarVenda(null,true);
        tela.setVisible(true);
    }//GEN-LAST:event_botVendas1ActionPerformed

    private void botVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVendasActionPerformed
        // TODO add your handling code here:
        JDialogRealizarVenda tela = new JDialogRealizarVenda(null,true);
        tela.setVisible(true);
    }//GEN-LAST:event_botVendasActionPerformed

    private void botAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAbrirCaixaActionPerformed
        // TODO add your handling code here:
        JDialogAbrirCaixa tela = new JDialogAbrirCaixa(null, true, usuLogado);
        tela.setVisible(true);
        //        JOptionPane.showMessageDialog(this, "Caixa já aberto!");
    }//GEN-LAST:event_botAbrirCaixaActionPerformed

    private void botClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botClienteActionPerformed
        // TODO add your handling code here:
        JDialogCliente tela = new JDialogCliente(null,true);
        tela.setVisible(true);
    }//GEN-LAST:event_botClienteActionPerformed

    private void botUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botUsuarios1ActionPerformed
        // TODO add your handling code here:

        //        if(this.usuario.getUsCargo().toLowerCase().equals("gerente")){
            //            JDialogUsuario tela = new JDialogUsuario(null,true);
            //            tela.setVisible(true);
            //        }else{
            JDialogMudarSenha tela1 = new JDialogMudarSenha(this, true);
            tela1.setUsu(this.usuario);
            tela1.setVisible(true);

            //        }
    }//GEN-LAST:event_botUsuarios1ActionPerformed

    private void botRealizarRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRealizarRecebimentoActionPerformed
        // TODO add your handling code here:
        JDialogRecebimentoVenda tela = new JDialogRecebimentoVenda(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_botRealizarRecebimentoActionPerformed

    private void botRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRelatorioVendasActionPerformed
        // TODO add your handling code here:
        JDialogRelatorioDataVendasPagas tela = new JDialogRelatorioDataVendasPagas(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_botRelatorioVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> {
        //  new TelaPrincipal().setVisible(true);
        /*    JDialogCliente frame1 = new JDialogCliente(new JFrame(), true);
            frame1.setContentPane(new TelaPrincipal());
            frame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame1.pack();
            frame1.setLocationRelativeTo(null);
            frame1.setVisible(true);
        });
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> {
        //  new TelaPrincipalGerente().setVisible(true);
        /*    JDialogCliente frame1 = new JDialogCliente(new JFrame(), true);
            frame1.setContentPane(new TelaPrincipalGerente());
            frame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame1.pack();
            frame1.setLocationRelativeTo(null);
            frame1.setVisible(true);
        });
    }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAbrirCaixa;
    private javax.swing.JButton botCliente;
    private javax.swing.JButton botDespesa;
    private javax.swing.JButton botFecharCaixa;
    private javax.swing.JButton botRealizarRecebimento;
    private javax.swing.JButton botRelatorioCaixa;
    private javax.swing.JButton botRelatorioRecebimento;
    private javax.swing.JButton botRelatorioVendas;
    private javax.swing.JButton botUsuarios1;
    private javax.swing.JButton botVendas;
    private javax.swing.JButton botVendas1;
    private javax.swing.JPanel conteudo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

  

}
